export const DEFAULT_UNITS = [
  { code: 'kg', name: 'Kilogramo' },
  { code: 'g', name: 'Gramo' },
  { code: 'ton', name: 'Tonelada' },
  { code: 'bolsa', name: 'Bolsa' },
  { code: 'saco', name: 'Saco' },
  { code: 'l', name: 'Litro' },
  { code: 'ml', name: 'Mililitro' },
  { code: 'm', name: 'Metro' },
  { code: 'cm', name: 'Centimetro' },
  { code: 'm2', name: 'Metro Cuadrado' },
  { code: 'm3', name: 'Metro Cubico' },
  { code: 'un', name: 'Unidad' },
  { code: 'par', name: 'Par' },
  { code: 'doc', name: 'Docena' },
  { code: 'rollo', name: 'Rollo' },
  { code: 'barra', name: 'Barra' },
  { code: 'plancha', name: 'Plancha' },
  { code: 'gl', name: 'Global' },
  { code: 'hr', name: 'Hora' },
  { code: 'dia', name: 'Dia' },
] as const;
